apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 00-ns.yaml
- 01-deployment.yaml
- 02-service.yaml
namespace: prueba-create
images:
- name: gcr.io/google-samples/hello-app:2.0
  newName: chzgustavo/hello-gitops
  newTag: fcb68e0abe12c051186e1d6593a041100cf64618
